name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run JMeter Action on a test
      uses: rbhadti94/apache-jmeter-action@v0.5.0
      with:
        testFilePath: MyFirstTestPlan.jmx
        outputReportsFolder: reports/
        args: "--loglevel INFO"
          
